CHANGELOG.md, gradle.properties, posthog/src/main/java/com/posthog/android/payloads/ScreenPayload.java, posthog/src/test/java/com/posthog/android/payloads/ScreenPayloadTest.java
In iOS we push `$screen_name` key with the screen that the event occurred on. Let's change this to match that for consistent reporting in Posthog.
=> Change screen key to $screen_name to match ios

posthog/src/main/java/com/posthog/android/PostHog.java, posthog/src/test/java/com/posthog/android/PostHogTest.java
- Capture calls were incorrectly handling defaultOptions object
- This PR ensures that sending feature flag option will be handled correctly
=> Make sure defaultOptions are configured on capture calls

posthog/src/main/java/com/posthog/android/PostHogFeatureFlags.java, posthog/src/test/java/com/posthog/android/PostHogFeatureFlagsTest.java
Feature flag tests were failing because there was no distinct ID being set
=> Fix feature flags tests with missing distinct ID

.github/workflows/android.yml, posthog/src/test/java/com/posthog/android/MiddlewareTest.java, posthog/src/test/java/com/posthog/android/PostHogBuilderTest.java, posthog/src/test/java/com/posthog/android/payloads/GroupPayloadTest.java
Set up android test CI and fix failing tests 🙈
=> Create android library test CI

.github/workflows/android.yml
Previously we were only running on pull requests, but this means that we
don't get test results for the master branch. This is a problem because
we want to know if the master branch is broken before we perform a
release of the App. We could enforce that all PRs must be up to date
with master, but this is a bit of a pain and doesn't really solve the
problem of knowing for sure that master is broken.
=> ci: run tests on master as well

CHANGELOG.md, USAGE.md, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Closes https://github.com/PostHog/posthog-android/pull/15
=> Add `distinctId()` getter to the Public API

.github/workflows/danger.yml, dangerfile.js
Do not forget changelog entries
=> Add Danger changelog checker

posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidContext.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogAndroidContextTest.kt
Just a typo
https://github.com/PostHog/posthog/blob/94405b0532013045c3ea9a39e6234b8152eca2d2/frontend/src/lib/taxonomy.tsx#L220
=> Fix `device_type` typo

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/build.gradle.kts, posthog-android/lint-baseline.xml
Apps using Java 8 won't be able to use the SDK
AGP 7.x already requires Java 11 but not everyone is able to migrate older projects.
=> Add compatibility to Java 8 bytecode (previously Java 11+)

CHANGELOG.md, posthog/build.gradle.kts, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/test/java/com/posthog/PostHogConfigTest.kt, posthog/src/test/java/com/posthog/internal/PostHogApiTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt
By doing https://github.com/PostHog/posthog-android/pull/41 I noticed that `isFeatureEnabled` is also wrong.
I also noticed that the iOS SDK never returns `false` if a flag has a `false` value.
https://github.com/PostHog/posthog-ios/blob/9298825fe26899a58b976d400254e0b050daa578/PostHog/Classes/PHGPostHog.m#L317
Is it a bug on the iOS SDK I believe, right?
=> isFeatureEnabled now returns true if multivariant flag

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt, posthog/src/test/java/com/posthog/Utils.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt
https://github.com/PostHog/posthog-ios-recorder/pull/6#discussion_r1354591017
=> SDK only sends the  event once per flag

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogAppInstallIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogSharedPreferences.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogSharedPreferencesTests.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MainActivity.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/main/java/com/posthog/PostHogInternal.kt, posthog/src/main/java/com/posthog/internal/PostHogApi.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/main/java/com/posthog/internal/PostHogPreferences.kt, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt, posthog/src/main/java/com/posthog/internal/PostHogSerializer.kt, posthog/src/test/java/com/posthog/internal/PostHogApiTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt, posthog/src/test/java/com/posthog/internal/PostHogSendCachedEventsIntegrationTest.kt, posthog/src/test/java/com/posthog/internal/PostHogSendCachedLegacyEventsIntegrationTest.kt
After talking to @neilkakkar, we confirmed that groups should be cached in the disk otherwise customers would have to register the groups every time the SDK is set up.
The Android SDK v2 didn't do groups at all.
=> Groups are cached in the disk

posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/resources/json/alias.json, posthog/src/test/resources/json/basic-event.json, posthog/src/test/resources/json/batch-request.json, posthog/src/test/resources/json/capture.json, posthog/src/test/resources/json/identify.json, posthog/src/test/resources/json/other-event.json
No need to duplicate the `distinct_id` in the properties as well.
the Backend already checks for this field as top level or within the properties, but the top level is preferred.
_#skip-changelog_ since its just internal
=> `distinct_id` is always a top level property only

.github/workflows/build.yml, .github/workflows/gradle-wrapper-validation.yml, CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogSharedPreferences.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogSharedPreferencesTests.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MainActivity.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/main/java/com/posthog/internal/PostHogMemoryPreferences.kt, posthog/src/main/java/com/posthog/internal/PostHogPreferences.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Closes https://github.com/PostHog/posthog-android/issues/50
=> Cache registered properties

CHANGELOG.md, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt
If device was disconnected, the flushing boolean would never be flipped
Found by https://github.com/PostHog/posthog-android/pull/53/files#r1365940959
Real device and unit test
=> Keep trying to flush events till the device is connected

CHANGELOG.md, posthog-android/consumer-rules.pro
If proguard/R8 is enabled, the tooling can decide to remove classes that are called at runtime but are not referenced directly (eg via reflection), or rename fields that would break serialization that depends on reflection eg Gson.
=> Ship proguard rules for proguard/r8 full mode

CHANGELOG.md, USAGE.md, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Discussed on https://github.com/PostHog/posthog-ios/pull/78
=> Remove properties from `identify` and `alias`

CHANGELOG.md, posthog-samples/posthog-android-sample/build.gradle.kts, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt, posthog/src/main/java/com/posthog/internal/PostHogApi.kt, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt
StrictMode revealed that some resources were not closed.
Also added a memory leak detector
=> Fix leaked resources identified by StrictMode

CHANGELOG.md, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Unblock migration https://github.com/djamoapp/posthog-flutter/blob/ae8b77bb776e4d32882b2f61cdebf9fe45dbae34/lib/src/posthog.dart#L81-L84
=> Expose and allow to enable and disable the debug mode at runtime

CHANGELOG.md, gradle.properties, posthog-android/build.gradle.kts, posthog-android/consumer-rules.pro, posthog-samples/posthog-android-sample/build.gradle.kts
> java.lang.RuntimeException: Failed to invoke constructor 'com.posthog.PostHogEvent()' with no args.
If Proguard/R8 removed the classes/methods/ctor not referenced directly.
https://github.com/google/gson/blob/2658aca66a1d0f097794a5ad5eb33c095a8f8d5d/gson/src/main/java/com/google/gson/internal/ConstructorConstructor.java#L273C39-L273C67
* Consumer file was not picked up correctly since it was set twice/and a typo.
* Issue reported by a user.
Running the sample with R8 enabled.
=> Pick up consumer proguard rules correctly

buildSrc/src/main/java/PostHogPublishConfig.kt
Relates to https://github.com/gradle/gradle/issues/20210 and causes:
> posthog-android/posthog-android/buildSrc/src/main/java/PostHogPublishConfig.kt:58:41 'getter for buildDir: File' is deprecated. Deprecated in Java
`buildDir` already fallback to `layout.buildDirectory.asFile.get()` so there's nothing to be done, just warning elimitation.
=> Updated deprecated buildDir Gradle

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidContext.kt
=> Do not set network carrier if empty

CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/build.gradle.kts, posthog-samples/posthog-android-sample/build.gradle.kts, posthog/build.gradle.kts
* Kotlin 1.5 is deprecated.
* Ref. for the latest toolchain tooling https://blog.blundellapps.co.uk/setting-jdk-level-in-android-gradle-builds/
=> Bump Kotlin to min. 1.6 compatibility

CHANGELOG.md, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt
https://github.com/postHog/posthog-js-lite/ sends events regardless the timer if `flush` is called manually.
https://posthog.com/questions/flush-interval-seconds-not-working
=> flush forcefully sends events regardless the delay

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/ViewTreeSnapshotStatus.kt, posthog-samples/posthog-android-sample/build.gradle.kts
https://posthog.com/questions/status-bar-color-not-updating
I recall fixing something [similar](https://github.com/getsentry/sentry-java/pull/1769) in the past as well.
Sometimes the new APIs (setOnApplyWindowInsetsListener) are not well documented on when and how to use them, this is just another weird corner case/side effect.
Testing the sample app with a different theme and status colors
=> fix: Check keyboard status during snapshot instead of using WindowInsets listener

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt
The event Queue was paused even if there were no errors, so setting a lower `flushIntervalSeconds` did not have a lot of effects.
The `Do not report flag events if the flag has been reported with the same value` fix part of this PR was found after fixing the main issue and was necessary to be in the same PR to make the CI happy.
=> fix: Events Queue is only paused if there were errors

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
When there are keyboard events (open/close), the view is redrawn and the wireframe has a new `height` due to making space for the keyboard hence the wireframe observed a mutation.
The mutation sends just the wireframe but not its children leading to all children being lost in the FE since its stateless.
https://us.posthog.com/project/41706/replay/5e3d9268-1d86-4d10-81dc-82239b885a40
=> fix: Send wireframe children for updated wireframes - mutation

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/PostHogAndroid.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogLifecycleObserverIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/PostHogLogCatIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/PostHogLogCatWatcher.kt, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogLifecycleObserverIntegrationTest.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/NormalActivity.kt, posthog-samples/posthog-android-sample/src/main/res/layout/normal_activity.xml, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/main/java/com/posthog/PostHogOkHttpInterceptor.kt
If session replay was disabled or session not active, console logs and network requests were still captured since the check was done only early in the app lifecycle.
Running both with session replay and session active and not active
=> Do not capture console logs and network requests if session replay and session are not active

posthog/src/main/java/com/posthog/internal/PostHogApiError.kt
`.` isn't helpful since it was inferred from the message only.
https://posthog.com/questions/not-able-to-trigger-any-event
=> chore: improve API error message

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog/src/main/java/com/posthog/internal/GzipRequestInterceptor.kt
Set `Content-Length` header for `gzip` bodies because of more strict proxies
https://posthog.com/questions/not-able-to-trigger-any-event
Testing using a self hosted version given by the user
=> Set `Content-Length` header for `gzip` bodies because of more strict proxies

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/internal/replay/RRStyle.kt
Also sending status and navigation bar
=> chore: gradient backgrounds support

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Same as https://github.com/PostHog/posthog-ios/pull/107
=> fix reset session when reset or close are called

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, gradle.properties, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-samples/posthog-android-sample/build.gradle.kts
1.  Dependency 'androidx.lifecycle:lifecycle-livedata-core-ktx:2.7.0' requires libraries and applications that
depend on it to compile against version 34 or later of the
Android APIs.
:app is currently compiled against android-33.
Also, the maximum recommended compile SDK version for Android Gradle
plugin 7.4.2 is 33.
Recommended action: Update this project's version of the Android Gradle
plugin to one that supports 34, then update this project to use
compileSdkVerion of at least 34.
There were more like this, we cannot force people to use the latest version.
=> roll back compile API to 33 to keep back compatibility

buildSrc/build.gradle.kts, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog/src/main/java/com/posthog/internal/PostHogDecideResponse.kt
.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
It should not affect anything since we still set `languageVersion` to 1.6, so just optimizations and bug fixes.
=> bump kotlin tooling

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/internal/PostHogApi.kt, posthog/src/main/java/com/posthog/internal/PostHogDecideRequest.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/test/java/com/posthog/PostHogTest.kt, posthog/src/test/java/com/posthog/internal/PostHogApiTest.kt, posthog/src/test/java/com/posthog/internal/PostHogDecideRequestTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt
https://posthog.com/docs/product-analytics/identify#what-happens-if-you-call-identify-or-alias-with-invalid-inputs
A customer has events with empty `$anon_distinct_id` which is likely a side effect of calling `identify` with an empty `distinct_id`, adding some validations and loggings.
Just running it, tests are in place for non nullable fields at least
=> do not allow empty or blank `distinct_id` or `anon_distinct_id`

CHANGELOG.md, buildSrc/build.gradle.kts, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/lint-baseline.xml
Reverts https://github.com/PostHog/posthog-android/pull/99
Fixes https://github.com/PostHog/posthog-android/issues/103
Okhttp and Okio were upgraded to Kotlin 1.8 https://square.github.io/okhttp/changelogs/changelog_4x/#version-4120
Downgrade Okhttp upgraded in this [PR](https://github.com/PostHog/posthog-android/pull/86)
Created an empty project using Kotlin 1.7
=> fix back compatibility with Kotlin 1.7

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
$groups were only sent if you were capturing events with `groupProperties`.
bug found by @Lior539 
unit test.
=> fix merge groups for events

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt
Fixes https://github.com/PostHog/posthog-flutter/issues/89
For some reason, the companion object const val (aka static in Java) isn't available when the `sessionId` is declared
The non companion object vars are created before the companion object ones so the `sessionId` was assigned with null instead of `sessionIdNone`, static code analyzer should have gotten that.
Bug introduced by #105
=> fix do not allow nullable sessionId

CHANGELOG.md, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/replay/PostHogDrawableConverter.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt
Drawables using https://github.com/mikepenz/Android-Iconics/blob/develop/iconics-core/src/main/java/com/mikepenz/iconics/IconicsDrawable.kt won't be possible to convert to Bitmap automatically
```
sessionReplayConfig.drawableConverter = PostHogDrawableConverter { drawable ->
if (drawable is IconicsDrawable) {
drawable.toBitmap()
}
null
}
```
=> chore: custom drawable converter

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-samples/posthog-android-sample/src/main/res/layout/normal_activity.xml
=> recording: do not capture password text even if masking is off

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/test/java/com/posthog/PostHogConfigTest.kt
`User-Agent` was still posthog-java for Android
=> fix: set correct User-Agent for Android and returns session recording even if authorized domains is enabled

CHANGELOG.md, USAGE.md, gradle.properties, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/Debouncer.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/NextDrawListener.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt, posthog/src/main/java/com/posthog/internal/replay/RRWireframe.kt
Adds a screenshot with high-fidelity UI instead of the wireframe option.
Adds more overhead to the app.
Enables Session replay for apps using Jetpack Compose.
The mutation updates seem to be buggy, waiting for @pauldambra so we can pair up on that, won't merge before this.
Running the sample and some open source apps
=> recording: add `screenshot` option for session replay instead of wireframe

CHANGELOG.md, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt
Getting Flushing failed: PostHogApiError(statusCode=413, message=''). depending on the image size and batch size
Running and unit tests
=> fix: reduce batch size if API returns 413

CHANGELOG.md, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
this makes it aligned with the js/ts sdk
- https://github.com/PostHog/posthog-js/blob/55694356e168568700f3370f26d636cbe09bf795/src/posthog-core.ts#L169
- https://github.com/PostHog/posthog-ios/pull/133
unit test
=> allow anonymous uuid generation to be customizable

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/NextDrawListener.kt
Fixes https://github.com/PostHog/posthog-android/issues/133
=> recording: fix removing the ViewTreeObserver when its not alive

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/internal/NextDrawListener.kt
sometimes the SDK inits so early that the view isn't attached yet.
running and debugging before view is attached
=> recording: fix registering the ViewTreeObserver when its not attached yet

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
Events from https://play.google.com/sdk-console v3.3.1
Exception java.lang.IllegalStateException: Fragment already added
at androidx.fragment.app.Fragment.setInitialSavedState (Fragment.java:833)
at <private>
at android.view.View.layout (View.java:24475)
at android.view.ViewGroup.layout (ViewGroup.java:7383)
at <private>
at android.view.View.layout (View.java:24475)
at android.view.ViewGroup.layout (ViewGroup.java:7383)
at <private>
at android.view.View.layout (View.java:24475)
at android.view.ViewGroup.layout (ViewGroup.java:7383)
at <private>
at android.view.View.layout (View.java:24475)
at android.view.ViewGroup.layout (ViewGroup.java:7383)
at android.widget.FrameLayout.layoutChildren (FrameLayout.java:332)
at android.widget.FrameLayout.onLayout (FrameLayout.java:270)
at …
=> recording: OnTouchEventListener try catch guard to swallow unexpected errors

CHANGELOG.md, USAGE.md, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/internal/PostHogLifecycleObserverIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogSharedPreferences.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/NextDrawListener.kt
Appium and friends may use `tag` or `content-desc` for finding/tagging elements
https://appium.readthedocs.io/en/stable/en/commands/element/find-elements/
https://reactnative.dev/docs/accessibility#accessibilitylabel syncs down to `content-desc` on Android
Masks webviews on Android screenshots
=> - recording: mask views with contentDescription setting and mask WebView if any masking is enabled

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt, posthog-android/src/test/java/com/posthog/android/Utils.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegrationTest.kt
The loadLabel method was loading the application label when an activity label was not defined. This change ensures that when an activity label is not defined, it defaults to the activity name instead of the application label. This improves the accuracy of screen name logging.
fix #150 
- Unit tests were updated and run to verify the behavior of the new activityLabelOrName method.
- Additional test scenarios were added to ensure that the correct labels are returned when activity and application labels are the same or empty.
- Verified that existing tests pass without any issues.
=> fix: ensure activity name is used when activity label is not defined

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidContext.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogAndroidContextTest.kt
This PR adds emulator detection to the static context and updates the tests to verify this functionality.
- Implemented `isEmulator` method to detect if the app is running on an emulator.
- Integrated emulator detection into the static context cache.
- Added assertions to verify emulator detection in the static context.
- Ensured static context includes the new `\$is_emulator` property.
A crucial property for future use as a filter.
#113 
The tests have been updated to include checks for the new `\$is_emulator` property in the static context.
I tested it manually on both an emulator and a physical device.
=> feat: add emulator detection property to static context

posthog-android/src/main/java/com/posthog/android/PostHogAndroid.kt
Noticed while debugging an issue on Flutter
https://github.com/PostHog/posthog-flutter/blob/b1d38521d98f47e54308867c11b96a63fd773fcc/android/src/main/kotlin/com/posthog/posthog_flutter/PosthogFlutterPlugin.kt#L54-L55
checked the captured event
=> fix: maintain sdk name and version for flutter

posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/test/java/com/posthog/Utils.kt, posthog/src/test/java/com/posthog/internal/PostHogQueueTest.kt
I was looking at the logs and trying to find the event id based on the logs but they don't match, they should
matching the ids
=> chore: file name in storage matches the event uuid

CHANGELOG.md, gradle.properties, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidContext.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt
"thread 5" tid=5 Runnable
#00  pc 0x000000000005c070  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
#01  pc 0x000000000014a873  /apex/com.android.art/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+82)
#02  pc 0x00000000004d6cdb  /apex/com.android.art/lib/libart.so (art::GoToRunnable(art::Thread*)+298)
#03  pc 0x00000000004d6b91  /apex/com.android.art/lib/libart.so (art::JniMethodEnd(unsigned int, art::Thread*)+8)
at android.os.BinderProxy.transactNative (Native method)
at android.os.BinderProxy.transact (BinderProxy.java:571)
at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfo (IConnectivityManager.java:1669)
at android.net.ConnectivityManager.getNetworkInfo (ConnectivityManager.java:1346)
at …
=> chore: use getNetworkCapabilities instead of getNetworkInfo to avoid ANRs

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
"main" tid=1 Native
#00  pc 0x000000000009eeb8  /apex/com.android.runtime/lib64/bionic/libc.so (fsync+8)
#01  pc 0x0000000000004700  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_Sync+20)
#02  pc 0x0000000000022404  /apex/com.android.art/lib64/libopenjdk.so (FileDescriptor_sync+40)
#03  pc 0x0000000000351e30  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144)
#04  pc 0x00000000005b9a30  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
#05  pc 0x000000000043c184  /system/framework/framework.jar (android.os.FileUtils.sync+12)
at <private>
#07  pc 0x00000000005ba854  /apex/com.android.art/lib64/libart.so (nterp_helper+7636)
at <private>
#09  pc 0x00000000005b99d4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
at <private>
#11  pc …
=> recording: capture touch interaction off of main thread to avoid ANRs

CHANGELOG.md, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/main/java/com/posthog/internal/PostHogSessionManager.kt
Exposes session id, similar to [JS](https://github.com/PostHog/posthog-js/blob/82fd8399b0bc13b43e354fa3cd407ab82b3d2105/src/posthog-core.ts#L1517-L1526)
Exposes a setter but not publically
there are unit tests already, only refactored to its class so it is accessible (the getter) but not the setter via the public API
=> chore: expose session id

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
found during the https://github.com/PostHog/posthog-android/pull/167 testing
when reset is called, the session id was set to null, so the next events wouldn't contain a session id anymore, in this case, the correct behaviour would be just rotating the session id.
this would affect session recording as well.
=> fix: rotate session id when reset is called

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Closes https://github.com/PostHog/posthog-android/issues/169
=> fix: do not clear events and reload flags after reset is called

posthog/src/main/java/com/posthog/internal/PostHogQueue.kt
There was not enough logging with debug enabled if something goes wrong.
=> chore: more network logging

posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidContext.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogAndroidContextTest.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MyApp.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/internal/PostHogContext.kt
Recordings were appending groups wrongly
Recordings didn't have SDK info
_#skip-changelog_ since its not a user facing change
=> chore: sdk info in recordings

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/PostHogLogCatIntegration.kt, posthog-android/src/test/java/com/posthog/android/PostHogFake.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/main/java/com/posthog/PostHogOkHttpInterceptor.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/main/java/com/posthog/internal/PostHogPreferences.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt, posthog/src/test/resources/json/basic-decide-recording.json
Similar to https://github.com/PostHog/posthog-ios/pull/150
If replay is active in the SDK config but disabled in the project settings, a recording would start and would end after ~1s when the decide API finishes.
=> fix: respect session replay project settings from app start

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
follow up https://github.com/PostHog/posthog-android/pull/179
the window is already attached but we don't have the callback yet so we need to allow this
=> recording: react native has window attached but needs view ready callback

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt, posthog-android/src/test/java/com/posthog/android/Utils.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegrationTest.kt
#138
Added tests to include checks for `$referrer` and `$referring_domain` properties in case of referrals from apps and websites.
=> add referrer url automatically

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
Tries to fix https://github.com/PostHog/posthog-react-native-session-replay/issues/4
It's unclear if PostHog SDK is responsible for that, since the SDK intercepts the touch, the SDK will be always part of the stack trace, it does not mean its the SDK causing it.
=> recording: OnTouchEventListener try catch guard to swallow unexpected errors take 2

posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt
expose getApplicationInfo
less code on the flutter plugin the better
=> chore: expose getApplicationInfo

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt
Relates to https://github.com/PostHog/posthog-react-native-session-replay/issues/10
Running method out of the main thread
It should not crash from the main thread anyway but for some reason, it does for that issue
=> recording: fix crash when calling view.isVisible

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/api/posthog-android.api, posthog-android/build.gradle.kts, posthog-android/consumer-rules.pro, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/replay/PostHogMaskModifier.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-samples/posthog-android-sample/src/main/java/com/posthog/android/sample/MainActivity.kt
Fix  #158
Tested on a sample app. Auto as well as manual masking using `Modifier.postHogMaskReplay()`, both working as expected.
=> feat: add replay masking to jetpack compose views

CHANGELOG.md, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
Tries to close https://github.com/PostHog/posthog-android/issues/203
Running the sample with compose screen
=> recording: fix observation on multiple threads in layout/draw is not supported for compose

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt
Relates to https://github.com/PostHog/posthog-flutter/issues/120
@ioannisj we will need that for iOS as well
Reason is here https://github.com/PostHog/posthog-flutter/issues/120#issuecomment-2469771444
=> fix: allow changing person properties after identify

USAGE.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt
@ioannisj mind doing it on iOS?
I will fix RN and the docs.
=> fix: usage and some comments

CHANGELOG.md, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
flutter already captures screenshots, we dont want to do it twice, we still need the replay integration
=> fix: recording for flutter does not capture screenshots on both sides

CHANGELOG.md, posthog-android/api/posthog-android.api, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
File Info
• Resolution: 1080×2400
• MIME type: image/octet-stream
• Extension: bin
• Size: 6.69 KB
• Download: image.bin
WEBP_LOSSY
File Info
• Resolution: 1080×2400
• MIME type: image/octet-stream
• Extension: bin
• Size: 310.68 KB
• Download: image.bin
WEBP_LOSSLESS
File Info
• Resolution: 1080×2400
• MIME type: image/octet-stream
• Extension: bin
• Size: 6.69 KB
• Download: image.bin
WEBP or WEBP_LOSSY
File Info
• Resolution: 1080×2400
• MIME type: image/png
• Extension: png
• Size: 20.45 KB
• Download: image.png
• Bit depth: 8
PNG
File Info
• Resolution: 1080×2400
• MIME type: image/jpeg
• Extension: jpg
• Size: 20.25 KB
• Download: image.jpg
• Channels: 3
• Bit depth: 8
JPEG
Also this https://github.com/PostHog/posthog-ios/blob/5dceb9b86f6c65c1dcc6d18ae97e1face7236636/PostHog/Replay/P …
=> chore: change screenshot image type from JPEG to WEBP

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/PostHogAndroidConfig.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt, posthog/src/main/java/com/posthog/PostHogConfig.kt
https://github.com/postHog/posthog.com
=> chore: session replay - ga

CHANGELOG.md, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogAppInstallIntegration.kt, posthog-android/src/main/java/com/posthog/android/internal/PostHogLifecycleObserverIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/PostHogLogCatIntegration.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegrationTest.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogAppInstallIntegrationTest.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogLifecycleObserverIntegrationTest.kt, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogIntegration.kt, posthog/src/main/java/com/posthog/PostHogOkHttpInterceptor.kt, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt, posthog/src/main/java/com/posthog/internal/replay/RRUtils.kt, posthog/src/test/java/com/posthog/FakePostHogIntegration.kt, posthog/src/test/java/com/posthog/internal/PostHogSendCachedEventsIntegrationTest.kt, posthog/src/test/java/com/posthog/internal/PostHogSendCachedLegacyEventsIntegrationTest.kt
Closes https://github.com/PostHog/posthog-android/issues/216
=> fix: session replay and auto capture works with 'with' method

CHANGELOG.md, posthog-android/lint-baseline.xml, posthog/src/main/java/com/posthog/internal/PostHogDecideResponse.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt
with https://github.com/PostHog/posthog/pull/28564, we now start to respond different with the /decide and /local_evaluation APIs if users have gone over their quota limit. Now we need to change the SDKs to handle these new responses.
=> feat(feature-flags): support quota limiting for feature flags

CHANGELOG.md, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt
Closes https://github.com/PostHog/posthog-android/issues/231
I cannot reproduce this issue.
I cannot mock the serializer right now, since the catch block already deletes the file, I just did the same if the serializer returns null.
=> chore: delete queue files if serialization fails

CHANGELOG.md, posthog-android/consumer-rules.pro
Likely fix https://github.com/PostHog/posthog-flutter/issues/171
Proguard/r8 is minifying the remote config response, which depends on reflection
=> fix: add remote config response to proguard rules

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/internal/PostHogRemoteConfig.kt, posthog/src/test/java/com/posthog/PostHogTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsV3Test.kt
Changes `isFeatureEnabled` to delegate to `getFeatureFlag` in order to get the result. This ensures that the `$feature_flag_called` event sends the correct `$feature_flag_response`.
This is the same change I made in https://github.com/PostHog/posthog-ios/pull/337.
Unit tests
=> fix: Reimplement `isfeatureEnabled` using `getFeatureFlag`

CHANGELOG.md, posthog-android/lint-baseline.xml, posthog/src/main/java/com/posthog/internal/PostHogRemoteConfig.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt
fix for https://github.com/PostHog/posthog-ios/pull/346#discussion_r2066856115
=> fix: clear cache if there are no active flags server side

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
Closes https://github.com/PostHog/posthog-js/issues/2233
I cannot reproduce this issue, but I added a few checks to check the state of the view, this should at least avoid most of the crashes.
Side effect is that if the view is in any of that state, the snapshot will be missed, but it should capture the next if all is fine.
Running and checking that everything works as it should, but I cannot reproduce the issue.
=> fix: do not try to use the view if it is in a dirty state

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
Closes https://github.com/PostHog/posthog-js/issues/2298
Just running the app but I cant reproduce the issue anyway
=> fix: prevent circular reference in the view hierarchy where a child view somehow references back to a parent, creating an infinite loop

CHANGELOG.md, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogCoreInterface.kt, posthog/src/main/java/com/posthog/PostHogInterface.kt, posthog/src/main/java/com/posthog/PostHogStateless.kt, posthog/src/main/java/com/posthog/PostHogStatelessInterface.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlagsInterface.kt, posthog/src/main/java/com/posthog/internal/PostHogQueue.kt, posthog/src/main/java/com/posthog/internal/PostHogQueueInterface.kt, posthog/src/main/java/com/posthog/internal/PostHogRemoteConfig.kt, posthog/src/test/java/com/posthog/PostHogStatelessTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt
This is a revival of #225:
- Create PostHogStateless base class
- Add PostHogStatelessInterface
- Refactor PostHog to extend PostHogStateless
- Update all method signatures to use stateless pattern
- Add stateless tests
Additionally, the goal here is to avoid introducing any functional changes to the Android SDK or public interfaces.
Related to https://github.com/PostHog/posthog/issues/16419
To expand the core library to support stateless server-side Java applications. Additional Java interoperability changes should follow in another release.
According to the previous PR:
> No new server-side code here, so existing Android tests should suffice for confidence in these changes.
I've added additional unit tests to validate stateless behavior.
=> feat(java-sdk): Add a server-side stateless interface

RELEASING.md
#skip-changelog
The document references the wrong script. `prepare-release.sh` is the script that bumps version, commits and pushes tags. `bump-version.sh` only performs the former.
=> doc: Reference the correct release script

posthog-server/CHANGELOG.md, posthog-server/api/posthog-server.api, posthog-server/src/main/java/com/posthog/server/PostHogConfig.kt, posthog-server/src/test/java/com/posthog/server/PostHogConfigTest.kt, posthog/CHANGELOG.md, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/main/java/com/posthog/PostHogStateless.kt, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlagCalledCache.kt, posthog/src/test/java/com/posthog/PostHogStatelessTest.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagCalledCacheTest.kt
From documentation:
> *Note:* Tracking whether it's a new user or if a flag value has changed happens in a local cache. This means that if you reinitialize the PostHog client, the cache resets as well – causing `$feature_flag_called` events to be sent again when calling `getFeatureFlag` or `isFeatureEnabled`. PostHog is built to handle this, and so duplicate `$feature_flag_called` events won't affect your analytics.
This appears not to have been true of the `PostHogStateless` client. This PR fixes that.
Additional unit tests. Some unrelated [Android tests are failing](https://github.com/PostHog/posthog-android/issues/292) and I'll be looking into that shortly in another PR.
=> fix(core): Deduplicate `$feature_flag_called` events

posthog-server/CHANGELOG.md, posthog-server/build.gradle.kts, posthog-server/src/main/java/com/posthog/server/internal/PostHogFeatureFlagCache.kt, posthog-server/src/test/java/com/posthog/server/internal/PostHogFeatureFlagCacheTest.kt
Flag caching was needlessly performing linear time operations when it could have been constant.
Existing tests are passing.
=> fix(server): Cache feature flag responses in constant time

build.gradle.kts, buildSrc/src/main/java/PostHogPublishConfig.kt, posthog-android/build.gradle.kts, posthog-server/build.gradle.kts, posthog/build.gradle.kts
#skip-changelog
All modules currently share a single description, "SDK for posthog.com". This is visible from Maven Central.
Instead of centralizing version or having a single description per module, each module is now responsible for setting their own version (still managed centrally via gradle.properties) and POM description.
Viewing the POMs generated via:
```sh
./gradlew :posthog:generatePomFileForMavenPublication
./gradlew :posthog-android:generatePomFileForReleasePublication
./gradlew :posthog-server:generatePomFileForMavenPublication
```
We now have:
| Module          | Version | Description                                           |
|-----------------|---------|-------------------------------------------------------|
| posthog         | 3.23.1  | Core library for PostHog SDKs …
=> chore: Modules define their own POM properties

posthog-server/CHANGELOG.md, posthog-server/build.gradle.kts, posthog-server/src/main/java/com/posthog/server/PostHogConfig.kt, posthog-server/src/main/java/com/posthog/server/internal/PostHogServerContext.kt, posthog-server/src/test/java/com/posthog/server/internal/PostHogServerContextTest.kt
SDK info such as `$lib` and `$lib_version` was not being set in event properties. Similarly, the user agent used for API requests reflected the core library instead.
=> fix(server): Correctly identify the SDK User-Agent

posthog-server/CHANGELOG.md, posthog-server/USAGE.md, posthog-server/api/posthog-server.api, posthog-server/src/main/java/com/posthog/server/PostHog.kt, posthog-server/src/main/java/com/posthog/server/PostHogCaptureOptions.kt, posthog-server/src/main/java/com/posthog/server/PostHogInterface.kt, posthog-server/src/test/java/com/posthog/server/PostHogCaptureOptionsTest.kt, posthog-server/src/test/java/com/posthog/server/PostHogTest.kt, posthog/CHANGELOG.md, posthog/api/posthog.api, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogStateless.kt, posthog/src/main/java/com/posthog/PostHogStatelessInterface.kt, posthog/src/test/java/com/posthog/PostHogStatelessTest.kt
Some users wish to use their own timestamps when capturing an event to ensure order of events. This change allows users to set their own timestamps when capturing an event.
Unit tests and local testing via the sample Java project
=> feat: Allow stateless override of event timestamp
