PostHog/posthog-android

.gitignore, posthog-samples/posthog-sample/build.gradle, posthog-samples/posthog-sample/src/main/java/com/posthog/android/sample/MainActivity.java, posthog-samples/posthog-sample/src/main/java/com/posthog/android/sample/SampleApp.java, posthog-samples/posthog-sample/src/main/res/layout/activity_main.xml, posthog-samples/posthog-sample/src/main/res/values/strings.xml, posthog-samples/posthog-wear-sample/build.gradle, posthog/build.gradle, posthog/src/main/java/com/posthog/android/Client.java, posthog/src/main/java/com/posthog/android/ConnectionFactory.java, posthog/src/main/java/com/posthog/android/Integration.java, posthog/src/main/java/com/posthog/android/IntegrationOperation.java, posthog/src/main/java/com/posthog/android/Persistence.java, posthog/src/main/java/com/posthog/android/PostHog.java, posthog/src/main/java/com/posthog/android/PostHogFeatureFlags.java, posthog/src/main/java/com/posthog/android/Properties.java, posthog/src/main/java/com/posthog/android/internal/Utils.java, posthog/src/main/java/com/posthog/android/payloads/BasePayload.java, posthog/src/main/java/com/posthog/android/payloads/CapturePayload.java, posthog/src/main/java/com/posthog/android/payloads/GroupPayload.java, posthog/src/main/java/com/posthog/android/payloads/IdentifyPayload.java, posthog/src/main/java/com/posthog/android/payloads/ScreenPayload.java, posthog/src/test/java/com/posthog/android/PersistenceTest.java, posthog/src/test/java/com/posthog/android/PostHogFeatureFlagsTest.java, posthog/src/test/java/com/posthog/android/PostHogTest.java, posthog/src/test/java/com/posthog/android/TestUtils.java, posthog/src/test/java/com/posthog/android/payloads/GroupPayloadTest.java
=> feat(libraries): add groups, multivar FF, continuity support for posthog-android

README.md
=> Add unit testing instructions

posthog/src/main/java/com/posthog/android/PostHog.java, posthog/src/test/java/com/posthog/android/PostHogTest.java
Reverts PostHog/posthog-android#17
=> Revert "Make sure defaultOptions are configured on capture calls"

posthog/src/main/java/com/posthog/android/PostHog.java, posthog/src/test/java/com/posthog/android/PostHogTest.java
https://github.com/PostHog/posthog-android/pull/17 didn't work in all cases. Couldn't identify why but reenabling it again using as small of a change as possible
=> chore: send feature flags by default

CHANGELOG.md
=> Add alpha.4 to changelog entry

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegration.kt, posthog-android/src/test/java/com/posthog/android/Utils.kt, posthog-android/src/test/java/com/posthog/android/internal/PostHogActivityLifecycleCallbackIntegrationTest.kt
Closes https://github.com/PostHog/posthog-android/issues/26
=> Does not report screen events if there's no title

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/test/java/com/posthog/PostHogTest.kt, posthog/src/test/resources/json/basic-decide-with-non-active-flags.json
Closes https://github.com/PostHog/posthog-android/issues/40
=> active_feature_flags event should filter non active flags

posthog/src/main/java/com/posthog/internal/PostHogDecideRequest.kt, posthog/src/test/java/com/posthog/internal/PostHogDecideRequestTest.kt, posthog/src/test/resources/json/decide-request.json
https://github.com/PostHog/posthog.com/pull/6921
=> change token to api_key for decide API

.github/ISSUE_TEMPLATE/feature_request.yml
=> Fix enhancement typo

.github/workflows/build.yml, .github/workflows/gradle-wrapper-validation.yml, CONTRIBUTING.md, README.md
=> Add development guide and badges

.github/workflows/release.yml, scripts/update-tag.sh
Similar to https://github.com/PostHog/posthog-ios/pull/88 but there's no side effect in this repository unless people checkout the branch and compile the SDK manually, but let's update the tag commit anyway just for the sake of being correct.
=> Update release tag

build.gradle.kts, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/build.gradle.kts, posthog/build.gradle.kts
=> Add Animal sniffer for Java 8 compat/Android classes

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/build.gradle.kts, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
chore: send custom keyboard event when keyboard is open or close
=> chore: send custom keyboard event when keyboard is open or close

CHANGELOG.md, buildSrc/src/main/java/PosthogBuildConfig.kt, posthog-android/lint-baseline.xml, posthog-android/src/main/java/com/posthog/android/PostHogAndroidConfig.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/ViewTreeSnapshotStatus.kt, posthog/api/posthog.api, posthog/build.gradle.kts, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/main/java/com/posthog/PostHogExperimental.kt, posthog/src/main/java/com/posthog/internal/replay/RRAddedNode.kt, posthog/src/main/java/com/posthog/internal/replay/RREvent.kt, posthog/src/main/java/com/posthog/internal/replay/RRIncrementalMutationData.kt, posthog/src/main/java/com/posthog/internal/replay/RRMutatedNode.kt, posthog/src/main/java/com/posthog/internal/replay/RRStyle.kt, posthog/src/main/java/com/posthog/internal/replay/RRWireframe.kt
=> chore: Add mutations

USAGE.md
=> chore: Amend the limitations with RN/Flutter not supported

posthog-android/lint-baseline.xml, posthog-samples/posthog-android-sample/build.gradle.kts, posthog-samples/posthog-android-sample/lint-baseline.xml, posthog-samples/posthog-android-sample/src/main/res/layout/nothing_activity.xml, posthog-samples/posthog-android-sample/src/main/res/values/strings.xml
CI is unhappy because the samples have new lint issues (new dep version)
https://github.com/PostHog/posthog-android/actions/runs/7487331564/job/20380156023
=> fix: lint samples

USAGE.md
=> chore: Improve authorized domains note

USAGE.md
=> chore: update usage for enabling session recording feature flag

README.md
=> fix: community page

buildSrc/build.gradle.kts, gradle.properties, posthog-android/build.gradle.kts, posthog-android/lint-baseline.xml, posthog-samples/posthog-android-sample/build.gradle.kts
Remove warnings and use the latest tooling
=> chore: bump AGP to 8.2

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
https://github.com/androidx/androidx/blob/50b428df7b3182e866ba0c5e8b717f41b1fc1dc9/appcompat/appcompat/src/main/java/androidx/appcompat/view/menu/ActionMenuItemView.java#L42 has a nullable hint despite being non nullable
=> fix: issue with nullable hint

USAGE.md
=> fix: remove limitations from session recording usage file

USAGE.md
=> chore: drawable converter usage

posthog-android/lint-baseline.xml, posthog/src/main/java/com/posthog/PostHogConfig.kt
this is not needed for a while already
=> fix: remove authorized domains docs

USAGE.md
=> chore: update readme with screenshot option

posthog-android/lint-baseline.xml, posthog-android/src/main/resources/META-INF/com/posthog/posthog-android/verification.properties
register to https://android-developers.googleblog.com/2024/05/build-better-safer-sdks-google-play-sdk-console.html
=> chore: register to sdk console

CHANGELOG.md, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/test/java/com/posthog/PostHogConfigTest.kt
the app host is still supported so its back compatible anyway
=> chore: change host to new address

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt, posthog-samples/posthog-android-sample/src/main/res/layout/normal_activity.xml
chore: screenshot masking
running with and w/o masking enabled.
we don't have UI tests set up yet to validate the changes.
=> chore: screenshot masking

CHANGELOG.md, posthog-android/api/posthog-android.api, posthog-android/src/main/java/com/posthog/android/PostHogAndroidConfig.kt, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt, posthog/src/main/java/com/posthog/PostHogOkHttpInterceptor.kt
https://posthog.com/questions/setup-using-android-java-project
//        PostHogAndroidConfig config = new PostHogAndroidConfig("key");
//        PostHogAndroidConfig config = new PostHogAndroidConfig("key", "host");
//        PostHogAndroidConfig config = new PostHogAndroidConfig("key", "host", true);
... etc using a Java file
=> chore: create ctor overloads for better Java DX

USAGE.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt
follow up https://github.com/PostHog/posthog.com/pull/9049/files
=> chore: Jetcompose views aren't redacted

posthog/src/main/java/com/posthog/PostHogOkHttpInterceptor.kt
Replaces https://github.com/PostHog/posthog-android/pull/174
=> fix: network log wrong timestamp

posthog/api/posthog.api, posthog/src/main/java/com/posthog/PersonProfiles.kt, posthog/src/main/java/com/posthog/PostHog.kt, posthog/src/main/java/com/posthog/PostHogConfig.kt, posthog/src/test/java/com/posthog/PostHogPersonProfilesTest.kt
follow up https://github.com/PostHog/posthog-android/pull/171
=> ref: person profiles enum is not internal

posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt
if the view is not added, the screenshot is not taken
=> recording: react native view not added

CHANGELOG.md, posthog/src/main/java/com/posthog/internal/PostHogFeatureFlags.kt, posthog/src/test/java/com/posthog/internal/PostHogFeatureFlagsTest.kt, posthog/src/test/resources/json/basic-decide-recording-bool-linked-disabled.json, posthog/src/test/resources/json/basic-decide-recording-bool-linked-enabled.json, posthog/src/test/resources/json/basic-decide-recording-bool-linked-variant-match.json, posthog/src/test/resources/json/basic-decide-recording-bool-linked-variant-not-match.json
Based on https://github.com/PostHog/posthog-ios/pull/209/files
=> recording: session replay respect feature flag variants

posthog-android/src/main/java/com/posthog/android/replay/PostHogSessionReplayConfig.kt
Follow up https://github.com/PostHog/posthog-android/pull/198
=> fix: java docs compose masking

CHANGELOG.md, posthog/src/main/java/com/posthog/internal/PostHogSendCachedEventsIntegration.kt
=> fix: sending cached events null check

CHANGELOG.md, posthog-android/lint-baseline.xml, posthog/src/main/java/com/posthog/internal/PostHogApi.kt
https://posthog.slack.com/archives/C03P7NL6RMW/p1747234656199779?thread_ts=1746463230.255959&cid=C03P7NL6RMW
=> feat: log request and payload requests if debug is enabled

.github/workflows/release.yml, buildSrc/src/main/java/PostHogPublishConfig.kt
Reverts PostHog/posthog-android#258
Error: https://github.com/PostHog/posthog-android/actions/runs/15560121625/job/43810058536
Contacted their support as requested
=> Revert "chore: new maven central"

.github/workflows/release.yml, buildSrc/src/main/java/PostHogPublishConfig.kt
Reverts PostHog/posthog-android#259
Another try after migration here https://central.sonatype.com/publishing/namespaces
#skip-changelog
=> Revert "Revert "chore: new maven central""

CHANGELOG.md, posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt, posthog-android/src/main/java/com/posthog/android/replay/internal/Throttler.kt
Relates to https://github.com/PostHog/posthog-js/issues/2308
I am not sure if it fixes so I will keep it open and ask for feedback first
=> fix: throttle mechanism wasn't thread safe
